# config/packages/api_platform.yaml
api_platform:
    mapping:
        paths:
            - '%kernel.project_dir%/src/Entity'
            - '%kernel.project_dir%/config/api_platform' # yaml or xml directory configuration]
    patch_formats:
        json: ['application/merge-patch+json']
    swagger:
        versions: [3]
    defaults:
        pagination_items_per_page: 10000 # Default value
#services:
#    # ...
#    location.building_filter:
#        parent: 'api_platform.doctrine.orm.search_filter'
#        arguments: [ { 'building.id': "exact" } ]
#        tags:  [ 'api_platform.filter' ]
