survos_base:
  theme: umbrella
  user_provider: security.user.provider.concrete.database_users
#  theme: start-bootstrap
#  menu:
#    enable: true
#    main_menu: survos_sidebar_menu
#    breadcrumb_menu: true
#

twig:
  globals:
    theme: umbrella
  paths:
    'vendor/survos/base-bundle/templates/umbrella': 'theme'
